Add pytorch-engine to build.gradle.
Might be necessary for djl.
Try to fix

```
INFO: An error occurred while building the embedding model
2024-09-18 01:28:56 [pool-2-thread-5] org.jabref.logic.ai.ingestion.model.UpdateEmbeddingModelTask.call()
INFO: Downloading embedding model...
2024-09-18 01:28:56 [JavaFX Application Thread] org.jabref.logic.ai.ingestion.model.JabRefEmbeddingModel.lambda$startRebuildingTask$1()
ERROR: An error occurred while building the embedding model: ai.djl.engine.EngineException: Failed to load PyTorch native library
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:90)
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:41)
2024-09-18 01:28:56 [JavaFX Application Thread] org.jabref.gui.JabRefDialogService.notify()
INFO: An error occurred while building the embedding model
        at ai.djl.api@0.30.0/ai.djl.engine.Engine.getEngine(Engine.java:190)
        at ai.djl.api@0.30.0/ai.djl.Model.newInstance(Model.java:99)
        at ai.djl.api@0.30.0/ai.djl.repository.zoo.BaseModelLoader.createModel(BaseModelLoader.java:224)
        at ai.djl.api@0.30.0/ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:165)
        at ai.djl.api@0.30.0/ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:151)
        at org.jabref@100.0.0/org.jabref.logic.ai.ingestion.model.DeepJavaEmbeddingModel.<init>(DeepJavaEmbeddingModel.java:23)
        at org.jabref@100.0.0/org.jabref.logic.ai.ingestion.model.UpdateEmbeddingModelTask.call(UpdateEmbeddingModelTask.java:65)
        at org.jabref@100.0.0/org.jabref.logic.ai.ingestion.model.UpdateEmbeddingModelTask.call(UpdateEmbeddingModelTask.java:20)
        at org.jabref@100.0.0/org.jabref.gui.util.UiTaskExecutor$1.call(UiTaskExecutor.java:188)
        at javafx.graphics@23/javafx.concurrent.Task$TaskCallable.call(Task.java:1401)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Thilo\.djl.ai\pytorch\2.4.0-cu124-win-x86_64\torch_cuda.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
        at java.base/java.lang.Runtime.load0(Runtime.java:852)
        at java.base/java.lang.System.load(System.java:2025)
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:379)
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:195)
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:82)
        at ai.djl.pytorch_engine@0.30.0/ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53)
```